//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresentationCapability.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Pen.
        /// </summary>
        internal static string BlackPen {
            get {
                return ResourceManager.GetString("BlackPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Highlighter.
        /// </summary>
        internal static string BlueHighlighter {
            get {
                return ResourceManager.GetString("BlueHighlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Pen.
        /// </summary>
        internal static string BluePen {
            get {
                return ResourceManager.GetString("BluePen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string CloseHotkey {
            get {
                return ResourceManager.GetString("CloseHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP Presentation.
        /// </summary>
        internal static string ConferencexpPresentation {
            get {
                return ResourceManager.GetString("ConferencexpPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Overwrite.
        /// </summary>
        internal static string ConfirmImageOverwriteCaption {
            get {
                return ResourceManager.GetString("ConfirmImageOverwriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation may overwrite existing images.  Are you sure you want to proceed?.
        /// </summary>
        internal static string ConfirmImageOverwriteMessage {
            get {
                return ResourceManager.GetString("ConfirmImageOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase All.
        /// </summary>
        internal static string EraseAll {
            get {
                return ResourceManager.GetString("EraseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser.
        /// </summary>
        internal static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during communication: {0}.
        /// </summary>
        internal static string ErrorDuringCommunication {
            get {
                return ResourceManager.GetString("ErrorDuringCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in opening {0}, error message: {1}.
        /// </summary>
        internal static string ErrorInOpening {
            get {
                return ResourceManager.GetString("ErrorInOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in opening {0}
        ///Type not supported.
        /// </summary>
        internal static string ErrorInOpeningFileType {
            get {
                return ResourceManager.GetString("ErrorInOpeningFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in opening {0}
        ///Version may be out of date.
        /// </summary>
        internal static string ErrorInOpeningVersion {
            get {
                return ResourceManager.GetString("ErrorInOpeningVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during navigation, the page might be absent or might be still in the download process.
        /// </summary>
        internal static string ErrorOccuredDuringNavigation {
            get {
                return ResourceManager.GetString("ErrorOccuredDuringNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while taking snapshot.  Your target snapshot window may be in an invalid state or closed..
        /// </summary>
        internal static string ErrorWhileTakingSnapshot {
            get {
                return ResourceManager.GetString("ErrorWhileTakingSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string FileHotkey {
            get {
                return ResourceManager.GetString("FileHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information, see http://cct.cs.washington.edu/downloads/CXP/
        ///
        ///Presentation : {0}
        ///{1}.
        /// </summary>
        internal static string ForMoreInformationSee {
            get {
                return ResourceManager.GetString("ForMoreInformationSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighter.
        /// </summary>
        internal static string Highlighter {
            get {
                return ResourceManager.GetString("Highlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing PowerPoint document....
        /// </summary>
        internal static string ImportingPowerpointDocument {
            get {
                return ResourceManager.GetString("ImportingPowerpointDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must be within the collection..
        /// </summary>
        internal static string IndexMustBeWithinTheCollection {
            get {
                return ResourceManager.GetString("IndexMustBeWithinTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Blank Slide.
        /// </summary>
        internal static string InsertBlankSlide {
            get {
                return ResourceManager.GetString("InsertBlankSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Screen Shot.
        /// </summary>
        internal static string InsertScreenShot {
            get {
                return ResourceManager.GetString("InsertScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime Highlighter.
        /// </summary>
        internal static string LimeHighlighter {
            get {
                return ResourceManager.GetString("LimeHighlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Slide.
        /// </summary>
        internal static string NextSlide {
            get {
                return ResourceManager.GetString("NextSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next Slide.
        /// </summary>
        internal static string NextSlideHotkey {
            get {
                return ResourceManager.GetString("NextSlideHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string OpenHotkey {
            get {
                return ResourceManager.GetString("OpenHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Remote....
        /// </summary>
        internal static string OpenRemote {
            get {
                return ResourceManager.GetString("OpenRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found!.
        /// </summary>
        internal static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen.
        /// </summary>
        internal static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PresentationCapabilityFMain.
        /// </summary>
        internal static string PresentationCapabilityFMain {
            get {
                return ResourceManager.GetString("PresentationCapabilityFMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation Help.
        /// </summary>
        internal static string PresentationHelp {
            get {
                return ResourceManager.GetString("PresentationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Slide.
        /// </summary>
        internal static string PreviousSlide {
            get {
                return ResourceManager.GetString("PreviousSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Previous Slide.
        /// </summary>
        internal static string PreviousSlideHotkey {
            get {
                return ResourceManager.GetString("PreviousSlideHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving Page:  {0} / {1}.
        /// </summary>
        internal static string ReceivingPage {
            get {
                return ResourceManager.GetString("ReceivingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving Page: 1 / {0}.
        /// </summary>
        internal static string ReceivingPage_of_ {
            get {
                return ResourceManager.GetString("ReceivingPage_of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Pen.
        /// </summary>
        internal static string RedPen {
            get {
                return ResourceManager.GetString("RedPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Current Slide.
        /// </summary>
        internal static string ResendCurrentSlide {
            get {
                return ResourceManager.GetString("ResendCurrentSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resending current slide....
        /// </summary>
        internal static string ResendingCurrentSlide {
            get {
                return ResourceManager.GetString("ResendingCurrentSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resending slides....
        /// </summary>
        internal static string ResendingSlides {
            get {
                return ResourceManager.GetString("ResendingSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtDocument == null.
        /// </summary>
        internal static string RtDocumentIsNull {
            get {
                return ResourceManager.GetString("RtDocumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Shot Information.
        /// </summary>
        internal static string ScreenShotInformation {
            get {
                return ResourceManager.GetString("ScreenShotInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Application.
        /// </summary>
        internal static string SelectApplication {
            get {
                return ResourceManager.GetString("SelectApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Screen Shot.
        /// </summary>
        internal static string SelectScreenShot {
            get {
                return ResourceManager.GetString("SelectScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending slides....
        /// </summary>
        internal static string SendingSlides {
            get {
                return ResourceManager.GetString("SendingSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide  {0} of {1}.
        /// </summary>
        internal static string Slide_Of_ {
            get {
                return ResourceManager.GetString("Slide_Of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide  -- of --.
        /// </summary>
        internal static string Slide_Of_Placeholder {
            get {
                return ResourceManager.GetString("Slide_Of_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Slide.
        /// </summary>
        internal static string SlideHotkey {
            get {
                return ResourceManager.GetString("SlideHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Show.
        /// </summary>
        internal static string SlideShow {
            get {
                return ResourceManager.GetString("SlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot of {0}.
        /// </summary>
        internal static string SnapshotOf {
            get {
                return ResourceManager.GetString("SnapshotOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshots of minimized windows cannot be taken.{0}Please restore or maximize the window..
        /// </summary>
        internal static string SnapshotsOfMinimizedWindows {
            get {
                return ResourceManager.GetString("SnapshotsOfMinimizedWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string ToolsHotkey {
            get {
                return ResourceManager.GetString("ToolsHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference leader tried to navigate to a page you have not recieved.  Try using the &quot;Resend All Slides&quot; button to resolve this issue..
        /// </summary>
        internal static string TryResendAllSlidesButton {
            get {
                return ResourceManager.GetString("TryResendAllSlidesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Page for current TOCNode.
        /// </summary>
        internal static string UnableToFindPage {
            get {
                return ResourceManager.GetString("UnableToFindPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected highlighter color &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedHighlighterColor {
            get {
                return ResourceManager.GetString("UnexpectedHighlighterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected pen color &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedPenColor {
            get {
                return ResourceManager.GetString("UnexpectedPenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value greater than MaxPageNum.
        /// </summary>
        internal static string ValueGreaterThanMaxpagenum {
            get {
                return ResourceManager.GetString("ValueGreaterThanMaxpagenum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whiteboard {0}.
        /// </summary>
        internal static string Whiteboard {
            get {
                return ResourceManager.GetString("Whiteboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whiteboard 1.
        /// </summary>
        internal static string Whiteboard1 {
            get {
                return ResourceManager.GetString("Whiteboard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whiteboard Session.
        /// </summary>
        internal static string WhiteboardSession {
            get {
                return ResourceManager.GetString("WhiteboardSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Highlighter.
        /// </summary>
        internal static string YellowHighlighter {
            get {
                return ResourceManager.GetString("YellowHighlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Pen.
        /// </summary>
        internal static string YellowPen {
            get {
                return ResourceManager.GetString("YellowPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first open a document..
        /// </summary>
        internal static string YouMustFirstOpenADocument {
            get {
                return ResourceManager.GetString("YouMustFirstOpenADocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first select a screen shot by clicking Select Screen Shot on the Slide menu, and then clicking the screen shot you want..
        /// </summary>
        internal static string YouMustFirstSelectAScreenShot {
            get {
                return ResourceManager.GetString("YouMustFirstSelectAScreenShot", resourceCulture);
            }
        }
    }
}
