//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP.ReflectorService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSR.LST.ConferenceXP.ReflectorService.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP Reflector Service
        ///Microsoft Research
        ///
        ///{0}
        ///
        ///For more information, see http://cct.cs.washington.edu/downloads/CXP/.
        /// </summary>
        internal static string AboutCxpReflectorServiceText {
            get {
                return ResourceManager.GetString("AboutCxpReflectorServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ConferenceXP Reflector Service.
        /// </summary>
        internal static string AboutCxpReflectorServiceTitle {
            get {
                return ResourceManager.GetString("AboutCxpReflectorServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The members ArrayList and IPAddress must be initialized before calling MemberLookup.
        /// </summary>
        internal static string ArrayListAndIPAddressMustBeInitiated {
            get {
                return ResourceManager.GetString("ArrayListAndIPAddressMustBeInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of created threads exceed the number of thread types defined..
        /// </summary>
        internal static string CreatedThreadsExceedThreadTypesDefined {
            get {
                return ResourceManager.GetString("CreatedThreadsExceedThreadTypesDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either IPv6 or IPv4 should be enabled.
        /// </summary>
        internal static string EnableEitherIPv6OrIPv4 {
            get {
                return ResourceManager.GetString("EnableEitherIPv6OrIPv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://cct.cs.washington.edu/project-wiki/index.php/ConferenceXP_Reflector_Service.
        /// </summary>
        internal static string HelpURLReflector {
            get {
                return ResourceManager.GetString("HelpURLReflector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid traffic type combination.
        /// </summary>
        internal static string InvalidTrafficTypeCombination {
            get {
                return ResourceManager.GetString("InvalidTrafficTypeCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6 not enabled in OS.  Ignoring IPv6 from app.config..
        /// </summary>
        internal static string IPv6NotEnabledInOs {
            get {
                return ResourceManager.GetString("IPv6NotEnabledInOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCtoUC {0} Listener Exception - {1}.
        /// </summary>
        internal static string MCtoUCListenerException {
            get {
                return ResourceManager.GetString("MCtoUCListenerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCtoUC thread terminating exception - {0}.
        /// </summary>
        internal static string MCtoUCThreadTerminatingException {
            get {
                return ResourceManager.GetString("MCtoUCThreadTerminatingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistrarServer: Network Error while receiving/sending request message. Client: {0} {1}.
        /// </summary>
        internal static string NetworkErrorReceivingSendingRequest {
            get {
                return ResourceManager.GetString("NetworkErrorReceivingSendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectorService started.
        /// </summary>
        internal static string ReflectorServiceStarted {
            get {
                return ResourceManager.GetString("ReflectorServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectorService starting exception {0}.
        /// </summary>
        internal static string ReflectorServiceStartingException {
            get {
                return ResourceManager.GetString("ReflectorServiceStartingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectorService stopped.
        /// </summary>
        internal static string ReflectorServiceStopped {
            get {
                return ResourceManager.GetString("ReflectorServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectorService stopping exception {0}.
        /// </summary>
        internal static string ReflectorServiceStoppingException {
            get {
                return ResourceManager.GetString("ReflectorServiceStoppingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistrarServer: Received Request: {0}.
        /// </summary>
        internal static string RegistrarServerReceivedRequest {
            get {
                return ResourceManager.GetString("RegistrarServerReceivedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistrarServer thread terminating exception - {0}.
        /// </summary>
        internal static string RegistrarServerThreadTerminating {
            get {
                return ResourceManager.GetString("RegistrarServerThreadTerminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket Disposing Error.
        /// </summary>
        internal static string SocketDisposingError {
            get {
                return ResourceManager.GetString("SocketDisposingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket Initialization Error.
        /// </summary>
        internal static string SocketInitializationError {
            get {
                return ResourceManager.GetString("SocketInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UCtoUCMC forwarder exception - TrafficType: {0}   Packet received from: {1}
        ///{2}.
        /// </summary>
        internal static string UCtoUCMCForwarderException {
            get {
                return ResourceManager.GetString("UCtoUCMCForwarderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicast client time out, IP: {0}.
        /// </summary>
        internal static string UnicastClientTimeOut {
            get {
                return ResourceManager.GetString("UnicastClientTimeOut", resourceCulture);
            }
        }
    }
}
