//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.MDShow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDShowManager.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The crossbar output pin is not routed to any of the physical connectors we are aware of..
        /// </summary>
        internal static string CrossbarOutputPinNotRouted {
            get {
                return ResourceManager.GetString("CrossbarOutputPinNotRouted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device does not support the IAMCrossbar interface!.
        /// </summary>
        internal static string DeviceDoesNotSupportError {
            get {
                return ResourceManager.GetString("DeviceDoesNotSupportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectShow ErrorText: {0}.
        /// </summary>
        internal static string DirectshowErrortext {
            get {
                return ResourceManager.GetString("DirectshowErrortext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device does not support the IAMAnalogVideoDecoder interface!.
        /// </summary>
        internal static string DoesNotSupportIAMAnalogVideoDecoder {
            get {
                return ResourceManager.GetString("DoesNotSupportIAMAnalogVideoDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device does not support the IAMVfwCaptureDialogs interface!.
        /// </summary>
        internal static string DoesNotSupportIAMVfwCaptureDialogs {
            get {
                return ResourceManager.GetString("DoesNotSupportIAMVfwCaptureDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter with moniker {0} not found..
        /// </summary>
        internal static string FilterMonikerNotFound {
            get {
                return ResourceManager.GetString("FilterMonikerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter with name {0} not found..
        /// </summary>
        internal static string FilterNameNotFound {
            get {
                return ResourceManager.GetString("FilterNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputPin count: {0}, index used: {1}.
        /// </summary>
        internal static string InputPinCount {
            get {
                return ResourceManager.GetString("InputPinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputPin provided is not from this device!.
        /// </summary>
        internal static string InputPinError {
            get {
                return ResourceManager.GetString("InputPinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index, must be &gt;= 0 and &lt; {0}, index provided: {1}.
        /// </summary>
        internal static string InvalidIndex {
            get {
                return ResourceManager.GetString("InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find CxpRtpFilters.ax in the local directory..
        /// </summary>
        internal static string MissingCxpRtpFiltersError {
            get {
                return ResourceManager.GetString("MissingCxpRtpFiltersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find ScreenScraperFilter.ax in the local directory..
        /// </summary>
        internal static string MissingScreenScraperFilterError {
            get {
                return ResourceManager.GetString("MissingScreenScraperFilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null is not a valid value for parameter &apos;rtpSender&apos;.
        /// </summary>
        internal static string NullRtpSenderError {
            get {
                return ResourceManager.GetString("NullRtpSenderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null is not a valid value for parameter &apos;start&apos;.
        /// </summary>
        internal static string NullStartError {
            get {
                return ResourceManager.GetString("NullStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputPin count: {0}, index used: {1}.
        /// </summary>
        internal static string OutputPinCount {
            get {
                return ResourceManager.GetString("OutputPinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputPin provided is not from this device!.
        /// </summary>
        internal static string OutputPinError {
            get {
                return ResourceManager.GetString("OutputPinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t RenderLocal when graph is already rendered.
        /// </summary>
        internal static string RenderLocalError {
            get {
                return ResourceManager.GetString("RenderLocalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtpSender.
        /// </summary>
        internal static string RtpSender {
            get {
                return ResourceManager.GetString("RtpSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;start&apos; parameter must be either the &apos;source&apos; or &apos;compressor&apos; filter.
        /// </summary>
        internal static string StartParameterError {
            get {
                return ResourceManager.GetString("StartParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert - {0} to Guid.
        /// </summary>
        internal static string UnableToConvertToGuid {
            get {
                return ResourceManager.GetString("UnableToConvertToGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a compressor that supports - {0}.
        /// </summary>
        internal static string UnableToFindACompressor {
            get {
                return ResourceManager.GetString("UnableToFindACompressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find audio compressor - {0}.
        /// </summary>
        internal static string UnableToFindAudioCompressor {
            get {
                return ResourceManager.GetString("UnableToFindAudioCompressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the default audio renderer - {0}.
        /// </summary>
        internal static string UnableToFindDefaultAudioRenderer {
            get {
                return ResourceManager.GetString("UnableToFindDefaultAudioRenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the default compressor - {0}.
        /// </summary>
        internal static string UnableToFindDefaultCompressor {
            get {
                return ResourceManager.GetString("UnableToFindDefaultCompressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find video compressor - {0}.
        /// </summary>
        internal static string UnableToFindVideoCompressor {
            get {
                return ResourceManager.GetString("UnableToFindVideoCompressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected filter category.
        /// </summary>
        internal static string UnexpectedFilterCategory {
            get {
                return ResourceManager.GetString("UnexpectedFilterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown filter category - {0}.
        /// </summary>
        internal static string UnknownFilterCategory {
            get {
                return ResourceManager.GetString("UnknownFilterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device&apos;s video standard does not map to any of the video standards we are aware of..
        /// </summary>
        internal static string VideoStandardDoesNotMap {
            get {
                return ResourceManager.GetString("VideoStandardDoesNotMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Media Audio V2.
        /// </summary>
        internal static string WindowsMediaAudioV2 {
            get {
                return ResourceManager.GetString("WindowsMediaAudioV2", resourceCulture);
            }
        }
    }
}
