//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.Net.Rtp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSR.LST.Net.Rtp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} pRtcpPacketExceptionacket: {1}, received: {2}.
        /// </summary>
        internal static string ActualPacketsDifferFromExpected {
            get {
                return ResourceManager.GetString("ActualPacketsDifferFromExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Privileges Required.
        /// </summary>
        internal static string AdministratorPrivilegesRequired {
            get {
                return ResourceManager.GetString("AdministratorPrivilegesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array sizes must agree.
        /// </summary>
        internal static string ArraySizesMustAgree {
            get {
                return ResourceManager.GetString("ArraySizesMustAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer does not end on a 32 bit boundary, buffer size: {0}, size % 4: {1}.
        /// </summary>
        internal static string BufferMustEndOnBoundary {
            get {
                return ResourceManager.GetString("BufferMustEndOnBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A BYE packet may contain more than one SSRC. Please use the  methods provided for appropriately manipulating SSRCs..
        /// </summary>
        internal static string BYEPacketMayContainMoreThan1SSRC {
            get {
                return ResourceManager.GetString("BYEPacketMayContainMoreThan1SSRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYE reason must be &lt;= {0} UTF8 bytes.
        /// </summary>
        internal static string BYEReasonBytesExceeded {
            get {
                return ResourceManager.GetString("BYEReasonBytesExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling a NextFrame method without first calling IsUsingNextFrame = true.
        /// </summary>
        internal static string CallingANextFrameMethod {
            get {
                return ResourceManager.GetString("CallingANextFrameMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call MoveNext() before calling Current().
        /// </summary>
        internal static string CallMovenextBeforeCallingCurrent {
            get {
                return ResourceManager.GetString("CallMovenextBeforeCallingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access Rtp methods on the RtpSession if not monitoring Rtp traffic!.
        /// </summary>
        internal static string CannotAccessRtpMethods {
            get {
                return ResourceManager.GetString("CannotAccessRtpMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create a stream if there is no participant to associate it with!.
        /// </summary>
        internal static string CantCreateAStreamNoParticipant {
            get {
                return ResourceManager.GetString("CantCreateAStreamNoParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CName conflict detected between two remote machines. Conflicting IP addresses are {0} &amp; {1}, conflicting CName is {2}.
        /// </summary>
        internal static string CNameConflictDetectedRemoteMachines {
            get {
                return ResourceManager.GetString("CNameConflictDetectedRemoteMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cName must be a valid string, preferrably something unique, like an email address.
        /// </summary>
        internal static string cNameMustBeAValidString {
            get {
                return ResourceManager.GetString("cNameMustBeAValidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound packets must end on a 32 bit boundary.
        /// </summary>
        internal static string CompoundPacketsMustEndOnBoundary {
            get {
                return ResourceManager.GetString("CompoundPacketsMustEndOnBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP Nodes Detected:.
        /// </summary>
        internal static string ConferencexpNodesDetected {
            get {
                return ResourceManager.GetString("ConferencexpNodesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data length must be &lt;= Rtp.MAX_PACKET_SIZE({0}) - RtcpHeader.SIZE({1}) - Rtp.SSRC_SIZE({2}) - NAME_SIZE({3}).
        /// </summary>
        internal static string DataLengthIncorrect {
            get {
                return ResourceManager.GetString("DataLengthIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping data packet: {0}, FecIndex: {1}, FrameIndex: {2}, TS: {3}.
        /// </summary>
        internal static string DroppingDataPacket {
            get {
                return ResourceManager.GetString("DroppingDataPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping fec packet: {0}, FecIndex: {1}, DataRangeMin: {2}.
        /// </summary>
        internal static string DroppingFecPacket {
            get {
                return ResourceManager.GetString("DroppingFecPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateCNameDetectedEvent - A duplicate of the local CName was detected on the network between {0} &amp; {1}, RtpListener shutting down.
        /// </summary>
        internal static string DuplicateCNameDetected {
            get {
                return ResourceManager.GetString("DuplicateCNameDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate CNAME was detected between {0} and {1}.  Connectivity testing terminating..
        /// </summary>
        internal static string DuplicateCnameWasDetected {
            get {
                return ResourceManager.GetString("DuplicateCnameWasDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate packet received!.
        /// </summary>
        internal static string DuplicatePacketReceived {
            get {
                return ResourceManager.GetString("DuplicatePacketReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate packet received in RtpStream - {0}.
        /// </summary>
        internal static string DuplicatePacketReceivedInRtpStream {
            get {
                return ResourceManager.GetString("DuplicatePacketReceivedInRtpStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calling an event delegate - {0}.
        /// </summary>
        internal static string ErrorCallingAnEventDelegate {
            get {
                return ResourceManager.GetString("ErrorCallingAnEventDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error disposing ConnectivityDetector.
        ///{0}.
        /// </summary>
        internal static string ErrorDisposingConnectivityDetector {
            get {
                return ResourceManager.GetString("ErrorDisposingConnectivityDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Disposing RtpListener 
        ///{0}.
        /// </summary>
        internal static string ErrorDisposingRtpListener {
            get {
                return ResourceManager.GetString("ErrorDisposingRtpListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during RtpSender.Send 
        ///{0}.
        /// </summary>
        internal static string ErrorDuringRtpSenderSend {
            get {
                return ResourceManager.GetString("ErrorDuringRtpSenderSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while disposing RtpSender: {0}.
        /// </summary>
        internal static string ErrorWhileDisposingRtpSender {
            get {
                return ResourceManager.GetString("ErrorWhileDisposingRtpSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not hooked - ParticipantRemovedEvent - {0}.
        /// </summary>
        internal static string EventNotHookedParticipantRemoved {
            get {
                return ResourceManager.GetString("EventNotHookedParticipantRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not hooked - ParticipantTimeoutEvent - {0}.
        /// </summary>
        internal static string EventNotHookedParticipantTimeout {
            get {
                return ResourceManager.GetString("EventNotHookedParticipantTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not hooked - RtpParticipantAddedEvent - {0}.
        /// </summary>
        internal static string EventNotHookedRtpParticipantAdded {
            get {
                return ResourceManager.GetString("EventNotHookedRtpParticipantAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not hooked - RtpStreamAddedEvent - {0}.
        /// </summary>
        internal static string EventNotHookedRtpStreamAdded {
            get {
                return ResourceManager.GetString("EventNotHookedRtpStreamAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not hooked - RtpStreamRemovedEvent - {0}.
        /// </summary>
        internal static string EventNotHookedRtpStreamRemoved {
            get {
                return ResourceManager.GetString("EventNotHookedRtpStreamRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not hooked - RtpStreamTimeoutEvent - {0}.
        /// </summary>
        internal static string EventNotHookedRtpStreamTimeout {
            get {
                return ResourceManager.GetString("EventNotHookedRtpStreamTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first packet in a compound RTCP packet must be an SR: {0} or RR: {1}, actual: {2}.
        /// </summary>
        internal static string FirstPacketMustBeSROrRR {
            get {
                return ResourceManager.GetString("FirstPacketMustBeSROrRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frame.Length should be &gt; 0, otherwise we&apos;d send a packet with no data..
        /// </summary>
        internal static string FrameLengthShouldBePositive {
            get {
                return ResourceManager.GetString("FrameLengthShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrameOutOfSequenceEvent - RtpStream: {0}, LostFrames:{1}, Message:{2}.
        /// </summary>
        internal static string FrameOutOfSequenceEvent {
            get {
                return ResourceManager.GetString("FrameOutOfSequenceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrameReceivedEvent - {0}.
        /// </summary>
        internal static string FrameReceivedEvent {
            get {
                return ResourceManager.GetString("FrameReceivedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header length and item count disagree!.
        /// </summary>
        internal static string HeaderLengthAndItemCountDisagree {
            get {
                return ResourceManager.GetString("HeaderLengthAndItemCountDisagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible arguments; you must specify a participant and intend to send RTP traffic if you are not receiving data.  Sending Rtcp data only is not a valid use case..
        /// </summary>
        internal static string IncompatibleArgumentsMessageLong {
            get {
                return ResourceManager.GetString("IncompatibleArgumentsMessageLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible arguments; you must specify a participant and intend to send RTP traffic if you are not receiving data..
        /// </summary>
        internal static string IncompatibleArgumentsMessageShort {
            get {
                return ResourceManager.GetString("IncompatibleArgumentsMessageShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible arguments - participant(null), rtpTraffic(true).
        /// </summary>
        internal static string IncompatibleArgumentsStatus {
            get {
                return ResourceManager.GetString("IncompatibleArgumentsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Frame Received -- Frame Lost.
        /// </summary>
        internal static string IncompleteFrameReceived {
            get {
                return ResourceManager.GetString("IncompleteFrameReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of null objects, expected:{0}, actual:{1}.
        /// </summary>
        internal static string IncorrectNumberOfNullObjects {
            get {
                return ResourceManager.GetString("IncorrectNumberOfNullObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid buffer length: {0}, must be: {1}.
        /// </summary>
        internal static string InvalidBufferLength {
            get {
                return ResourceManager.GetString("InvalidBufferLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ItemCount:{0}, must be &gt;=0 or &lt;=31.
        /// </summary>
        internal static string InvalidItemCount {
            get {
                return ResourceManager.GetString("InvalidItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length: {0}, must be &gt;=0 or &lt;= {1}.
        /// </summary>
        internal static string InvalidLength {
            get {
                return ResourceManager.GetString("InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPacketEvent - {0}.
        /// </summary>
        internal static string InvalidPacketEvent {
            get {
                return ResourceManager.GetString("InvalidPacketEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPacketInFrameEvent - RtpStream:{0}, Reason:{1}.
        /// </summary>
        internal static string InvalidPacketInFrameEvent {
            get {
                return ResourceManager.GetString("InvalidPacketInFrameEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version: {0}, current: {1}.
        /// </summary>
        internal static string InvalidVersion {
            get {
                return ResourceManager.GetString("InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPAddress: {0} is trying to remove stream (ssrc: {1}), owned by IPAddress: {2}.
        /// </summary>
        internal static string IPAddressTryingToRemoveString {
            get {
                return ResourceManager.GetString("IPAddressTryingToRemoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join request to server {0}:{1} for {2} failed. 
        ///{3}.
        /// </summary>
        internal static string JoinRequestToServerFailed {
            get {
                return ResourceManager.GetString("JoinRequestToServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave request to server {0}:{1} for {2} failed. 
        ///{3}.
        /// </summary>
        internal static string LeaveRequestToServerFailed {
            get {
                return ResourceManager.GetString("LeaveRequestToServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of data must be &gt;= 0.
        /// </summary>
        internal static string LengthOfDataMustBePositive {
            get {
                return ResourceManager.GetString("LengthOfDataMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is meant to be overridden in a derived class.
        /// </summary>
        internal static string MethodMeantToBeOverridden {
            get {
                return ResourceManager.GetString("MethodMeantToBeOverridden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be &gt;= 1.
        /// </summary>
        internal static string MustBePositive {
            get {
                return ResourceManager.GetString("MustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A compound RTCP packet must contain more than 1 packet, actual count: {0}.
        /// </summary>
        internal static string MustContainMoreThan1Packet {
            get {
                return ResourceManager.GetString("MustContainMoreThan1Packet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required, and must be {0} ASCII characters long.
        /// </summary>
        internal static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be {0} ASCII characters.
        /// </summary>
        internal static string NameLengthIncorrect {
            get {
                return ResourceManager.GetString("NameLengthIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a real SenderReport, not null.
        /// </summary>
        internal static string NeedARealSenderReport {
            get {
                return ResourceManager.GetString("NeedARealSenderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextFrame call has been unblocked, either manually or by the Dispose method.
        /// </summary>
        internal static string NextFrameCallHasBeenUnblocked {
            get {
                return ResourceManager.GetString("NextFrameCallHasBeenUnblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pivot row found!.
        /// </summary>
        internal static string NoPivotRowFound {
            get {
                return ResourceManager.GetString("NoPivotRowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null objects are not accepted.
        /// </summary>
        internal static string NullObjectsAreNotAccepted {
            get {
                return ResourceManager.GetString("NullObjectsAreNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On behalf of {0},
        ///{1}.
        /// </summary>
        internal static string OnBehalfOf {
            get {
                return ResourceManager.GetString("OnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided packet is not an fec packet!.
        /// </summary>
        internal static string PacketIsNotAnFECPacket {
            get {
                return ResourceManager.GetString("PacketIsNotAnFECPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a discrepancy between the number of padding bytes - actual: {0}, expected: {1}.
        /// </summary>
        internal static string PaddingBytesDiscrepancy {
            get {
                return ResourceManager.GetString("PaddingBytesDiscrepancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParticipantRemovedEvent - {0}.
        /// </summary>
        internal static string ParticipantRemovedEvent {
            get {
                return ResourceManager.GetString("ParticipantRemovedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParticipantStatusChangedEvent - Participant: {0}.
        /// </summary>
        internal static string ParticipantStatusChangedEvent {
            get {
                return ResourceManager.GetString("ParticipantStatusChangedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParticipantTimeoutEvent - {0}.
        /// </summary>
        internal static string ParticipantTimeoutEvent {
            get {
                return ResourceManager.GetString("ParticipantTimeoutEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSR.LST.Rtp.RtpPacketBase.PayloadType is a seven bit structure, and can hold values between 0 and 127.
        /// </summary>
        internal static string PayloadTypeIsASevenBitStructure {
            get {
                return ResourceManager.GetString("PayloadTypeIsASevenBitStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prefix.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PRIV item&apos;s prefix + data can not exceed {0} UTF8 bytes.
        /// </summary>
        internal static string PrefixAndDataBytesExceeded {
            get {
                return ResourceManager.GetString("PrefixAndDataBytesExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an unhandled Rtcp type, {0}.
        /// </summary>
        internal static string ReceivedAnUnhandledRtcpType {
            get {
                return ResourceManager.GetString("ReceivedAnUnhandledRtcpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectorEP not set properly.
        /// </summary>
        internal static string ReflectorEPNotSetProperly {
            get {
                return ResourceManager.GetString("ReflectorEPNotSetProperly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RtpListener buffer pool was growing unbounded.  We have stopped the receiving / distributing threads in order to prevent it from consuming all the RAM.
        /// </summary>
        internal static string RtpListenerBufferPoolGrowing {
            get {
                return ResourceManager.GetString("RtpListenerBufferPoolGrowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtpPacketFec does not support the TimeStamp property..
        /// </summary>
        internal static string RtpPacketFecDoesNotSupportTimestamp {
            get {
                return ResourceManager.GetString("RtpPacketFecDoesNotSupportTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtpParticipantAddedEvent - {0}.
        /// </summary>
        internal static string RtpParticipantAddedEvent {
            get {
                return ResourceManager.GetString("RtpParticipantAddedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtpSender already disposed.
        /// </summary>
        internal static string RtpSenderAlreadyDisposed {
            get {
                return ResourceManager.GetString("RtpSenderAlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtpSession does not contain a sender for the given SSRC - {0}.
        /// </summary>
        internal static string RtpSessionDoesNotContainASender {
            get {
                return ResourceManager.GetString("RtpSessionDoesNotContainASender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtpStreamAddedEvent - {0}.
        /// </summary>
        internal static string RtpStreamAddedEvent {
            get {
                return ResourceManager.GetString("RtpStreamAddedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtpStreamRemovedEvent - {0}.
        /// </summary>
        internal static string RtpStreamRemovedEvent {
            get {
                return ResourceManager.GetString("RtpStreamRemovedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtpStreamTimeoutEvent - {0}.
        /// </summary>
        internal static string RtpStreamTimeoutEvent {
            get {
                return ResourceManager.GetString("RtpStreamTimeoutEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SDES item&apos;s data can not exceed {0} UTF8 bytes: {1}, {2}.
        /// </summary>
        internal static string SDESItemDataBytesExceeded {
            get {
                return ResourceManager.GetString("SDESItemDataBytesExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SDES packet may contain more than one SSRC. Please use the  methods provided for appropriately manipulating SSRCs..
        /// </summary>
        internal static string SDESPacketMayContainMoreThan1SSRC {
            get {
                return ResourceManager.GetString("SDESPacketMayContainMoreThan1SSRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendAppPacket not allowed in Rtcp listening only mode..
        /// </summary>
        internal static string SendAppPacketNotAllowed {
            get {
                return ResourceManager.GetString("SendAppPacketNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSRC conflict detected between local sender and a sender at {0}.  Changing local sender ssrc..
        /// </summary>
        internal static string SSRCConflictDetectedLocalSender {
            get {
                return ResourceManager.GetString("SSRCConflictDetectedLocalSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSRC conflict detected between local session and a sender at {0}.  Changing session ssrc..
        /// </summary>
        internal static string SSRCConflictDetectedLocalSession {
            get {
                return ResourceManager.GetString("SSRCConflictDetectedLocalSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSRC conflict detected between two remote machines, conflicting IP address is {0}.
        /// </summary>
        internal static string SSRCConflictDetectedRemoteMachines {
            get {
                return ResourceManager.GetString("SSRCConflictDetectedRemoteMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap row not found!.
        /// </summary>
        internal static string SwapRowNotFound {
            get {
                return ResourceManager.GetString("SwapRowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one IntPtr of data to send.
        /// </summary>
        internal static string ThereMustBeAtLeastOneIntPtr {
            get {
                return ResourceManager.GetString("ThereMustBeAtLeastOneIntPtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeToLive should be &gt; 0.
        /// </summary>
        internal static string TimeToLiveShouldBePositive {
            get {
                return ResourceManager.GetString("TimeToLiveShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not have more than 31 items in an RtcpPacket.
        /// </summary>
        internal static string TooManyItems {
            get {
                return ResourceManager.GetString("TooManyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to grow the buffer pool after PoolMaxGrows has been reached.
        /// </summary>
        internal static string TryingToGrowTheBufferPool {
            get {
                return ResourceManager.GetString("TryingToGrowTheBufferPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected payload type!.
        /// </summary>
        internal static string UnexpectedPayloadType {
            get {
                return ResourceManager.GetString("UnexpectedPayloadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected SDES type: {0}.
        /// </summary>
        internal static string UnexpectedSDESType {
            get {
                return ResourceManager.GetString("UnexpectedSDESType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported role: {0}.
        /// </summary>
        internal static string UnsupportedRole {
            get {
                return ResourceManager.GetString("UnsupportedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value {0}  The maximum payload for this packet is: {1}.
        /// </summary>
        internal static string ValueMaximumPayload {
            get {
                return ResourceManager.GetString("ValueMaximumPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XOR can only produce 1 checksum packet.
        /// </summary>
        internal static string XORCanOnlyProduce1Checksum {
            get {
                return ResourceManager.GetString("XORCanOnlyProduce1Checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t set the padding bit on the first packet.
        /// </summary>
        internal static string YouCantSetThePaddingBit {
            get {
                return ResourceManager.GetString("YouCantSetThePaddingBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be an Administrator to install Rtp or run it for the first time..
        /// </summary>
        internal static string YouMustBeAnAdministratorToInstall {
            get {
                return ResourceManager.GetString("YouMustBeAnAdministratorToInstall", resourceCulture);
            }
        }
    }
}
