//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP.ReflectorService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSR.LST.ConferenceXP.ReflectorService.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP Reflector Service
        ///Microsoft Research and UW Center for Collaborative Technologies
        ///
        ///{0}
        ///
        ///For more information, see http://cct.cs.washington.edu/downloads/CXP/.
        /// </summary>
        internal static string AboutCxpReflectorServiceText {
            get {
                return ResourceManager.GetString("AboutCxpReflectorServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ConferenceXP Reflector Service.
        /// </summary>
        internal static string AboutCxpReflectorServiceTitle {
            get {
                return ResourceManager.GetString("AboutCxpReflectorServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Address.
        /// </summary>
        internal static string ClientAddress {
            get {
                return ResourceManager.GetString("ClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP Reflector.
        /// </summary>
        internal static string ConferenceXPReflector {
            get {
                return ResourceManager.GetString("ConferenceXPReflector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP Reflector Service Manager.
        /// </summary>
        internal static string ConferenceXPReflectorServiceManager {
            get {
                return ResourceManager.GetString("ConferenceXPReflectorServiceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Admin Tool could not connect to the service.  Please check to make sure that the ServiceName specified in the application configuration file is correct..
        /// </summary>
        internal static string ErrorConnectingText {
            get {
                return ResourceManager.GetString("ErrorConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Connecting.
        /// </summary>
        internal static string ErrorConnectingTitle {
            get {
                return ResourceManager.GetString("ErrorConnectingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Leave.
        /// </summary>
        internal static string ForceLeave {
            get {
                return ResourceManager.GetString("ForceLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Address : Port.
        /// </summary>
        internal static string GroupAddress {
            get {
                return ResourceManager.GetString("GroupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://cct.cs.washington.edu/project-wiki/index.php/ConferenceXP_Reflector_Service.
        /// </summary>
        internal static string HelpURLReflector {
            get {
                return ResourceManager.GetString("HelpURLReflector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Time.
        /// </summary>
        internal static string JoinTime {
            get {
                return ResourceManager.GetString("JoinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ConferenceXP Reflector Manager.
        /// </summary>
        internal static string OpenConferenceXPReflectorManager {
            get {
                return ResourceManager.GetString("OpenConferenceXPReflectorManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflector join port:.
        /// </summary>
        internal static string ReflectorJoinPort {
            get {
                return ResourceManager.GetString("ReflectorJoinPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflector Participants.
        /// </summary>
        internal static string ReflectorParticipants {
            get {
                return ResourceManager.GetString("ReflectorParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view Reflector participants, make sure the service is started, and then click the ConferenceXP Reflector Service Manager shortcut on the Start menu..
        /// </summary>
        internal static string ToViewReflectorParticipants {
            get {
                return ResourceManager.GetString("ToViewReflectorParticipants", resourceCulture);
            }
        }
    }
}
