//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSR.LST.ConferenceXP.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing file {0}
        ///{1}.
        /// </summary>
        internal static string AccessingFile {
            get {
                return ResourceManager.GetString("AccessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0}.
        /// </summary>
        internal static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Privileges Required.
        /// </summary>
        internal static string AdministratorPrivilegesRequired {
            get {
                return ResourceManager.GetString("AdministratorPrivilegesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot join a venue when already joined to a venue..
        /// </summary>
        internal static string AlreadyJoinedToVenue {
            get {
                return ResourceManager.GetString("AlreadyJoinedToVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is not configured to talk to a Venue Service.  Profile Update was discarded..
        /// </summary>
        internal static string ApplicationIsNotConfigured {
            get {
                return ResourceManager.GetString("ApplicationIsNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Capability: must call Send() before calling SendObject*().
        /// </summary>
        internal static string CallSendBeforeSendObject {
            get {
                return ResourceManager.GetString("CallSendBeforeSendObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A capability cannot be both a channel and owned..
        /// </summary>
        internal static string CannotBeChannelAndOwned {
            get {
                return ResourceManager.GetString("CannotBeChannelAndOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot exit a venue when not in a venue!.
        /// </summary>
        internal static string CannotExitNotInVenue {
            get {
                return ResourceManager.GetString("CannotExitNotInVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use Windows Form based capabilies from Conference Api unless you first set the Conference.CallingForm property.  Otherwise, we do not have the appropriate Windows Message Loop set up and the form creation will fail..
        /// </summary>
        internal static string CannotUseCapabilitiesUnless {
            get {
                return ResourceManager.GetString("CannotUseCapabilitiesUnless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capabilities collection already contains - {0}.
        /// </summary>
        internal static string CapabilitiesCollectionAlreadyContains {
            get {
                return ResourceManager.GetString("CapabilitiesCollectionAlreadyContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capability class {0} not found in CapabilitySenders.  Check Confernece.OtherCapabilitySenders for a list of valid CapabilitySender names..
        /// </summary>
        internal static string CapabilityClassNotFound {
            get {
                return ResourceManager.GetString("CapabilityClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capability.NameAttribute must be set.
        /// </summary>
        internal static string CapabilityNameAttributeMustBeSet {
            get {
                return ResourceManager.GetString("CapabilityNameAttributeMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapabilityParticipantAdded {0}:{1}.
        /// </summary>
        internal static string CapabilityParticipantAdded {
            get {
                return ResourceManager.GetString("CapabilityParticipantAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapabilityParticipantRemoved {0}:{1}.
        /// </summary>
        internal static string CapabilityParticipantRemoved {
            get {
                return ResourceManager.GetString("CapabilityParticipantRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capability.PayloadTypeAttribute must be set.
        /// </summary>
        internal static string CapabilityPayloadTypeMustBeSet {
            get {
                return ResourceManager.GetString("CapabilityPayloadTypeMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capability.Play() : {0}; {1}.
        /// </summary>
        internal static string CapabilityPlay {
            get {
                return ResourceManager.GetString("CapabilityPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capability.Send() : {0}; {1}.
        /// </summary>
        internal static string CapabilitySend {
            get {
                return ResourceManager.GetString("CapabilitySend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapabilitySender: {0}; {1}.
        /// </summary>
        internal static string CapabilitySender {
            get {
                return ResourceManager.GetString("CapabilitySender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapabilitySender already exists - {0}.
        /// </summary>
        internal static string CapabilitySenderAlreadyExists {
            get {
                return ResourceManager.GetString("CapabilitySenderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capability Timeout, {0}.
        /// </summary>
        internal static string CapabilityTimeout {
            get {
                return ResourceManager.GetString("CapabilityTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capability Timeout, ssrc == {0}.
        /// </summary>
        internal static string CapabilityTimeoutSSRC {
            get {
                return ResourceManager.GetString("CapabilityTimeoutSSRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapabilityViewer: {0}; {1}.
        /// </summary>
        internal static string CapabilityViewer {
            get {
                return ResourceManager.GetString("CapabilityViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapabilityViewer for PayloadType {0} not found!.
        /// </summary>
        internal static string CapabilityViewerNotFound {
            get {
                return ResourceManager.GetString("CapabilityViewerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtpSender did not originate from this capability!.
        /// </summary>
        internal static string DidNotOriginateFromHere {
            get {
                return ResourceManager.GetString("DidNotOriginateFromHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Capability Viewers Detected.
        /// </summary>
        internal static string DuplicateCapabilityViewersDetected {
            get {
                return ResourceManager.GetString("DuplicateCapabilityViewersDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate of the local Identity was detected on the network between {0} &amp; {1}.  Venue.Leave() has been called..
        /// </summary>
        internal static string DuplicateLocalIdentityError {
            get {
                return ResourceManager.GetString("DuplicateLocalIdentityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not appear to be a valid email address, sorry.
        /// </summary>
        internal static string EmailAddressInvalidText {
            get {
                return ResourceManager.GetString("EmailAddressInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Invalid.
        /// </summary>
        internal static string EmailAddressInvalidTitle {
            get {
                return ResourceManager.GetString("EmailAddressInvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erroneous image file.
        /// </summary>
        internal static string ErroneousImageFile {
            get {
                return ResourceManager.GetString("ErroneousImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Connecting to Venue Server.
        /// </summary>
        internal static string ErrorConnectingToVenueServer {
            get {
                return ResourceManager.GetString("ErrorConnectingToVenueServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Initializing Capability Classes.
        /// </summary>
        internal static string ErrorInitializingCapabilityClasses {
            get {
                return ResourceManager.GetString("ErrorInitializingCapabilityClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Initializing Capability Sender.
        /// </summary>
        internal static string ErrorInitializingCapabilitySender {
            get {
                return ResourceManager.GetString("ErrorInitializingCapabilitySender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Initializing Capability Viewer.
        /// </summary>
        internal static string ErrorInitializingCapabilityViewer {
            get {
                return ResourceManager.GetString("ErrorInitializingCapabilityViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FecRatio requires 2 ints in the form of a string, data:checksum.
        /// </summary>
        internal static string FecRatioRequires2Ints {
            get {
                return ResourceManager.GetString("FecRatioRequires2Ints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type cannot be read..
        /// </summary>
        internal static string FileTypeCannotBeRead {
            get {
                return ResourceManager.GetString("FileTypeCannotBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormType can not be null when calling CreateForm.
        /// </summary>
        internal static string FormTypeCanNotBeNull {
            get {
                return ResourceManager.GetString("FormTypeCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found duplicate CapabilitySender {0} in {1}.
        /// </summary>
        internal static string FoundDuplicateCapabilitySender {
            get {
                return ResourceManager.GetString("FoundDuplicateCapabilitySender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrameOutOfSequence, lostFrames = {0}, message = {1}, {2}.
        /// </summary>
        internal static string FrameOutOfSequenceMessage {
            get {
                return ResourceManager.GetString("FrameOutOfSequenceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrameOutOfSequence, lostFrames = {0}, message = {1}, ssrc == {2}.
        /// </summary>
        internal static string FrameOutOfSequenceMessageSSRC {
            get {
                return ResourceManager.GetString("FrameOutOfSequenceMessageSSRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue Service returned a participant with an indentifier not matching the requested identifier.  Participant was rejected.
        ///    Requested ID: {0}
        ///    Returned ID: {1}.
        /// </summary>
        internal static string IdentifierNotMatchingRequest {
            get {
                return ResourceManager.GetString("IdentifierNotMatchingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity:.
        /// </summary>
        internal static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Packet: {0}, {1}.
        /// </summary>
        internal static string InvalidPacketCV {
            get {
                return ResourceManager.GetString("InvalidPacketCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Packet: {0}, ssrc == {1}.
        /// </summary>
        internal static string InvalidPacketSSRC {
            get {
                return ResourceManager.GetString("InvalidPacketSSRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Packet, unknown CapabilityViewer, {0}.
        /// </summary>
        internal static string InvalidPacketUnknownCapabilityViewer {
            get {
                return ResourceManager.GetString("InvalidPacketUnknownCapabilityViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid venue: {0}.
        /// </summary>
        internal static string InvalidVenue {
            get {
                return ResourceManager.GetString("InvalidVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not join a venue that is of type Invalid.
        /// </summary>
        internal static string InvalidVenueType {
            get {
                return ResourceManager.GetString("InvalidVenueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Microsoft Windows Journal Viewer update has not been installed and it is required to run ConferenceXP..
        /// </summary>
        internal static string JournalViewerNotInstalled {
            get {
                return ResourceManager.GetString("JournalViewerNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaximumBandwidthLimiter must be between 0 and 100,000,000.
        /// </summary>
        internal static string MaximumBandwidthlimiterError {
            get {
                return ResourceManager.GetString("MaximumBandwidthlimiterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple capability viewers exist for payload type - {0}. 
        ///ConferenceXP selected {1} and will ignore {2}.
        /// </summary>
        internal static string MultipleCapabilityViewersExist {
            get {
                return ResourceManager.GetString("MultipleCapabilityViewersExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My icon.
        /// </summary>
        internal static string MyIcon {
            get {
                return ResourceManager.GetString("MyIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My information.
        /// </summary>
        internal static string MyInformation {
            get {
                return ResourceManager.GetString("MyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be between 1 and 255 characters long.
        /// </summary>
        internal static string NameLengthErrorText {
            get {
                return ResourceManager.GetString("NameLengthErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Length Error.
        /// </summary>
        internal static string NameLengthErrorTitle {
            get {
                return ResourceManager.GetString("NameLengthErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Timeout.
        /// </summary>
        internal static string NetworkTimeout {
            get {
                return ResourceManager.GetString("NetworkTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No form set for this Capability..
        /// </summary>
        internal static string NoFormSetForThisCapability {
            get {
                return ResourceManager.GetString("NoFormSetForThisCapability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PacketOutOfSequence, packets lost = {0}, {1}.
        /// </summary>
        internal static string PacketOutOfSequenceMessage {
            get {
                return ResourceManager.GetString("PacketOutOfSequenceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PacketOutOfSequence, packets lost = {0}, ssrc == {1}.
        /// </summary>
        internal static string PacketOutOfSequenceMessageSSRC {
            get {
                return ResourceManager.GetString("PacketOutOfSequenceMessageSSRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant icon must be less than 36 KB (a 96x96 pixel image)..
        /// </summary>
        internal static string ParticipantIconSizeErrorText {
            get {
                return ResourceManager.GetString("ParticipantIconSizeErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Icon Size Error.
        /// </summary>
        internal static string ParticipantIconSizeErrorTitle {
            get {
                return ResourceManager.GetString("ParticipantIconSizeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Timeout, {0}.
        /// </summary>
        internal static string ParticipantTimeout {
            get {
                return ResourceManager.GetString("ParticipantTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Timeout, CName == {0}.
        /// </summary>
        internal static string ParticipantTimeoutCName {
            get {
                return ResourceManager.GetString("ParticipantTimeoutCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing {0}.
        /// </summary>
        internal static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile could not be updated on the server.  Check that you have a connection to the venue server..
        /// </summary>
        internal static string ProfileCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("ProfileCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflector address not found - {0}.
        /// </summary>
        internal static string ReflectorAddressNotFound {
            get {
                return ResourceManager.GetString("ReflectorAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflector join request failed.
        /// </summary>
        internal static string ReflectorJoinRequestFailed {
            get {
                return ResourceManager.GetString("ReflectorJoinRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to access / remove a capability that is not in form&apos;s hashtable.
        /// </summary>
        internal static string RemoveCapabilityFormHashtable {
            get {
                return ResourceManager.GetString("RemoveCapabilityFormHashtable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to remove a capability that is not in FormType&apos;s hashtable.
        /// </summary>
        internal static string RemoveCapabilityFormTypeHashtable {
            get {
                return ResourceManager.GetString("RemoveCapabilityFormTypeHashtable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0}.
        /// </summary>
        internal static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A security error occurred connecting to the network (WSAEACCES).  Common causes of this error are; no network connection can be found, a change to the .NET Framework or Winsock without a reboot, or recently disconnecting from a VPN session which leaves Winsock in an indeterminate state.  Check your network connectivity or reboot your computer and try again..
        /// </summary>
        internal static string SecurityErrorOccurredConnecting {
            get {
                return ResourceManager.GetString("SecurityErrorOccurredConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending {0}.
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capability must specify the BackgroundSender attribute in order to have access to such an object.
        /// </summary>
        internal static string SpecifyBackgroundSenderAttribute {
            get {
                return ResourceManager.GetString("SpecifyBackgroundSenderAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped Playing {0}.
        /// </summary>
        internal static string StoppedPlaying {
            get {
                return ResourceManager.GetString("StoppedPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped Sending {0}.
        /// </summary>
        internal static string StoppedSending {
            get {
                return ResourceManager.GetString("StoppedSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream to add does not match the settings for this capability..
        /// </summary>
        internal static string StreamDoesNotMatchSettings {
            get {
                return ResourceManager.GetString("StreamDoesNotMatchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream lacks a CapabilityIdentifier in the external private extensions.  Streams without this are not supported by the ConferenceXP API..
        /// </summary>
        internal static string StreamLacksACapabilityidentifier {
            get {
                return ResourceManager.GetString("StreamLacksACapabilityidentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to add custom venue &apos;{0}&apos;, but that name is already in use..
        /// </summary>
        internal static string TryingToAddCustomVenue {
            get {
                return ResourceManager.GetString("TryingToAddCustomVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to call Send on a Capability when not in a venue..
        /// </summary>
        internal static string UnableToCallSend {
            get {
                return ResourceManager.GetString("UnableToCallSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Venue Service.  Using a default Venue: {0}.
        /// </summary>
        internal static string UnableToConnectUsingDefaultVenue {
            get {
                return ResourceManager.GetString("UnableToConnectUsingDefaultVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Venue Service, using a generic Participant: {0}.
        /// </summary>
        internal static string UnableToConnectUsingGenericParticipant {
            get {
                return ResourceManager.GetString("UnableToConnectUsingGenericParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Play a Capability when not in a venue..
        /// </summary>
        internal static string UnableToPlayACapability {
            get {
                return ResourceManager.GetString("UnableToPlayACapability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred connecting to the venue server.  Try again when you have a connection to the venue server. 
        ///
        ///Exception:
        ///{0}.
        /// </summary>
        internal static string UnexpectedConnectionError {
            get {
                return ResourceManager.GetString("UnexpectedConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value must be a Type.
        /// </summary>
        internal static string ValueMustBeAType {
            get {
                return ResourceManager.GetString("ValueMustBeAType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue server your profile is stored on could not be reached. Try again when you have a connection to the venue server..
        /// </summary>
        internal static string VenueServerCouldNotBeReached {
            get {
                return ResourceManager.GetString("VenueServerCouldNotBeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be an Administrator to install ConferenceXP or run it for the first time..
        /// </summary>
        internal static string YouMustBeAnAdministratorToInstall {
            get {
                return ResourceManager.GetString("YouMustBeAnAdministratorToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be an Administrator to uninstall ConferenceXP..
        /// </summary>
        internal static string YouMustBeAnAdministratorToUninstall {
            get {
                return ResourceManager.GetString("YouMustBeAnAdministratorToUninstall", resourceCulture);
            }
        }
    }
}
