//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP.ArchiveService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSR.LST.ConferenceXP.ArchiveService.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP Archive Service
        ///Microsoft Research &amp; UW Center for Collaborative Technologies
        ///
        ///{0}
        ///
        ///For more information, see http://cct.cs.washington.edu/downloads/CXP/.
        /// </summary>
        internal static string AboutArchiveServiceText {
            get {
                return ResourceManager.GetString("AboutArchiveServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ConferenceXP Archive Service.
        /// </summary>
        internal static string AboutArchiveServiceTitle {
            get {
                return ResourceManager.GetString("AboutArchiveServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Database.
        /// </summary>
        internal static string ArchiveDatabase {
            get {
                return ResourceManager.GetString("ArchiveDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://cct.cs.washington.edu/project-wiki/index.php/ConferenceXP_Archive_Service.
        /// </summary>
        internal static string ArchiverHelpURL {
            get {
                return ResourceManager.GetString("ArchiverHelpURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the .
        /// </summary>
        internal static string AreYouSureYouWantToDelete {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Up....
        /// </summary>
        internal static string CleanUp {
            get {
                return ResourceManager.GetString("CleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Clean Up Database feature removes the following records from your Archive Service database:
        /// - Conferences without participants
        /// - Participants without streams
        /// - Streams without recorded frames
        /// - Streams without raw data
        ///
        ///To complete these tasks, the Archive Service must be stopped. Clicking OK temporarily stops this service, causing any current conference recordings to stop..
        /// </summary>
        internal static string CleanUpDatabaseText {
            get {
                return ResourceManager.GetString("CleanUpDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Up Database.
        /// </summary>
        internal static string CleanUpDatabaseTitle {
            get {
                return ResourceManager.GetString("CleanUpDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference: {0} - {1}.
        /// </summary>
        internal static string Conference {
            get {
                return ResourceManager.GetString("Conference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conference: {0} - .
        /// </summary>
        internal static string ConferenceLower {
            get {
                return ResourceManager.GetString("ConferenceLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} conferences created from {1} at {2}\nto {3} at {4}?.
        /// </summary>
        internal static string ConfirmDeleteText {
            get {
                return ResourceManager.GetString("ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP Archive Service Manager.
        /// </summary>
        internal static string CXPArchiveServiceManager {
            get {
                return ResourceManager.GetString("CXPArchiveServiceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conference &quot;{0}&quot; and all the content it contains?.
        /// </summary>
        internal static string DeleteConference {
            get {
                return ResourceManager.GetString("DeleteConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder &quot;{0}&quot; and all the content it contains?.
        /// </summary>
        internal static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to participant &quot;{0}&quot; and all the content it contains?.
        /// </summary>
        internal static string DeleteParticipant {
            get {
                return ResourceManager.GetString("DeleteParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Range.
        /// </summary>
        internal static string DeleteRange {
            get {
                return ResourceManager.GetString("DeleteRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Range....
        /// </summary>
        internal static string DeleteRangeEllipsis {
            get {
                return ResourceManager.GetString("DeleteRangeEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stream &quot;{0}&quot;?.
        /// </summary>
        internal static string DeleteStream {
            get {
                return ResourceManager.GetString("DeleteStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} could not connect to the Microsoft SQL database. Ensure that the database is properly created and that the SqlConnectionString specified in the application configuration file is correct..
        /// </summary>
        internal static string ErrorConnectingToDatabaseText {
            get {
                return ResourceManager.GetString("ErrorConnectingToDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Connecting to Database.
        /// </summary>
        internal static string ErrorConnectingToDatabaseTitle {
            get {
                return ResourceManager.GetString("ErrorConnectingToDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} could not connect to the windows servce &quot;ConferenceXP Archive Service.&quot; Please check to make sure that the ServiceName specified in the application configuration file is correct..
        /// </summary>
        internal static string ErrorConnectingToServiceText {
            get {
                return ResourceManager.GetString("ErrorConnectingToServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Connecting to Service.
        /// </summary>
        internal static string ErrorConnectingToServiceTitle {
            get {
                return ResourceManager.GetString("ErrorConnectingToServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conferences were found during that time period..
        /// </summary>
        internal static string InvalidRangeText {
            get {
                return ResourceManager.GetString("InvalidRangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Range.
        /// </summary>
        internal static string InvalidRangeTitle {
            get {
                return ResourceManager.GetString("InvalidRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant: {0}.
        /// </summary>
        internal static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the conferences you want to delete by creation date:.
        /// </summary>
        internal static string SpecifyConferencesToDelete {
            get {
                return ResourceManager.GetString("SpecifyConferencesToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream: {0}.
        /// </summary>
        internal static string Stream {
            get {
                return ResourceManager.GetString("Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
    }
}
