//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSR.LST.ConferenceXP.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Added {1}.
        /// </summary>
        internal static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Venues:.
        /// </summary>
        internal static string AvailableVenues {
            get {
                return ResourceManager.GetString("AvailableVenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapabilitySender, {0}, does not implement ICapabilityWindow.
        /// </summary>
        internal static string CapabilitySenderDoesNotImplementICapabilityWindow {
            get {
                return ResourceManager.GetString("CapabilitySenderDoesNotImplementICapabilityWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First CapabilityViewer found, {0}, does not implement ICapabilityWindow.
        /// </summary>
        internal static string CapabilityViewerDoesNotImplementICapabilityWindow {
            get {
                return ResourceManager.GetString("CapabilityViewerDoesNotImplementICapabilityWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CyclePlayCapabilityViewers Test Run #{0}:.
        /// </summary>
        internal static string CyclePlayCapabilityViewersTestRun {
            get {
                return ResourceManager.GetString("CyclePlayCapabilityViewersTestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CycleSendVideo Test Run #{0}:.
        /// </summary>
        internal static string CycleSendVideoTestRun {
            get {
                return ResourceManager.GetString("CycleSendVideoTestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello ConferenceXP.
        /// </summary>
        internal static string HelloConferencexp {
            get {
                return ResourceManager.GetString("HelloConferencexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InAndOut Test Run #{0}:.
        /// </summary>
        internal static string InAndOutTestRun {
            get {
                return ResourceManager.GetString("InAndOutTestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined Venue {0} as {1}.
        /// </summary>
        internal static string JoinedVenue0As1 {
            get {
                return ResourceManager.GetString("JoinedVenue0As1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Venue {0}.
        /// </summary>
        internal static string JoiningVenue {
            get {
                return ResourceManager.GetString("JoiningVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving Venue {0}.
        /// </summary>
        internal static string LeavingVenue {
            get {
                return ResourceManager.GetString("LeavingVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Used: {0}, Diff: {1}.
        /// </summary>
        internal static string MemoryUsed {
            get {
                return ResourceManager.GetString("MemoryUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify an OtherCapabilityName in app.config using MSR.LST.ConferenceXP.PartSim.JoinAndSend.OtherCapabilityName.
        /// </summary>
        internal static string MustSpecifyAnOtherCapabilityName {
            get {
                return ResourceManager.GetString("MustSpecifyAnOtherCapabilityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CapabilityViewer found.  Cannot save window position..
        /// </summary>
        internal static string NoCapabilityViewerFound {
            get {
                return ResourceManager.GetString("NoCapabilityViewerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParticipantAdded: {0}.
        /// </summary>
        internal static string ParticipantAdded {
            get {
                return ResourceManager.GetString("ParticipantAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParticipantRemoved: {0}.
        /// </summary>
        internal static string ParticipantRemoved {
            get {
                return ResourceManager.GetString("ParticipantRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Played {1}.
        /// </summary>
        internal static string Played {
            get {
                return ResourceManager.GetString("Played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter to save the window position of the first playing capability.
        /// </summary>
        internal static string PressEnterToSavePlayingWindowPosition {
            get {
                return ResourceManager.GetString("PressEnterToSavePlayingWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter to save the window position of the sending capability.
        /// </summary>
        internal static string PressEnterToSaveSendingWindowPosition {
            get {
                return ResourceManager.GetString("PressEnterToSaveSendingWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Removed {1}.
        /// </summary>
        internal static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving window position for {0}.
        /// </summary>
        internal static string SavingWindowPosition {
            get {
                return ResourceManager.GetString("SavingWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started OtherCapabilitySender {0}.
        /// </summary>
        internal static string StartedOtherCapabilitySender {
            get {
                return ResourceManager.GetString("StartedOtherCapabilitySender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting JoinAndPlay.
        /// </summary>
        internal static string StartingJoinAndPlay {
            get {
                return ResourceManager.GetString("StartingJoinAndPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting JoinAndSend.
        /// </summary>
        internal static string StartingJoinAndSend {
            get {
                return ResourceManager.GetString("StartingJoinAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Stopped Playing {1}.
        /// </summary>
        internal static string StoppedPlaying {
            get {
                return ResourceManager.GetString("StoppedPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Run #{0}:.
        /// </summary>
        internal static string TestRun {
            get {
                return ResourceManager.GetString("TestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find an OtherCapabilitySender named &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToFindOtherCapabilitySender {
            get {
                return ResourceManager.GetString("UnableToFindOtherCapabilitySender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Venue {0}.
        /// </summary>
        internal static string UnableToFindVenue {
            get {
                return ResourceManager.GetString("UnableToFindVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid OtherCapabilitySenders:.
        /// </summary>
        internal static string ValidOtherCapabilitySenders {
            get {
                return ResourceManager.GetString("ValidOtherCapabilitySenders", resourceCulture);
            }
        }
    }
}
