//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSR.LST.ConferenceXP.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My audio is not being sent..
        /// </summary>
        internal static string AudioIsNotBeingSent {
            get {
                return ResourceManager.GetString("AudioIsNotBeingSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Settings.
        /// </summary>
        internal static string CameraSettings {
            get {
                return ResourceManager.GetString("CameraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not configure VFW driver-based cameras when in a venue.
        /// </summary>
        internal static string CanNotConfigureCamera {
            get {
                return ResourceManager.GetString("CanNotConfigureCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color not supported..
        /// </summary>
        internal static string ColorNotSupported {
            get {
                return ResourceManager.GetString("ColorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming audio is muted..
        /// </summary>
        internal static string IncomingAudioIsMuted {
            get {
                return ResourceManager.GetString("IncomingAudioIsMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming audio is not being sent or network connectivity has been lost..
        /// </summary>
        internal static string IncomingAudioIsNotBeingSent {
            get {
                return ResourceManager.GetString("IncomingAudioIsNotBeingSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming video is not being sent or network connectivity has been lost..
        /// </summary>
        internal static string IncomingVideoIsNotBeingSent {
            get {
                return ResourceManager.GetString("IncomingVideoIsNotBeingSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming video is paused. Other participants can still see your video..
        /// </summary>
        internal static string IncomingVideoIsPaused {
            get {
                return ResourceManager.GetString("IncomingVideoIsPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Audio.
        /// </summary>
        internal static string MuteAudio {
            get {
                return ResourceManager.GetString("MuteAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Video.
        /// </summary>
        internal static string PauseVideo {
            get {
                return ResourceManager.GetString("PauseVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Audio.
        /// </summary>
        internal static string PlayAudio {
            get {
                return ResourceManager.GetString("PlayAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Video.
        /// </summary>
        internal static string PlayVideo {
            get {
                return ResourceManager.GetString("PlayVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send My Audio.
        /// </summary>
        internal static string SendMyAudio {
            get {
                return ResourceManager.GetString("SendMyAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send My Video.
        /// </summary>
        internal static string SendMyVideo {
            get {
                return ResourceManager.GetString("SendMyVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Information.
        /// </summary>
        internal static string StatusInformation {
            get {
                return ResourceManager.GetString("StatusInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Normal.
        /// </summary>
        internal static string StatusNormal {
            get {
                return ResourceManager.GetString("StatusNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sending My Audio.
        /// </summary>
        internal static string StopSendingMyAudio {
            get {
                return ResourceManager.GetString("StopSendingMyAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sending My Video.
        /// </summary>
        internal static string StopSendingMyVideo {
            get {
                return ResourceManager.GetString("StopSendingMyVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My video is not being sent..
        /// </summary>
        internal static string VideoIsNotBeingSent {
            get {
                return ResourceManager.GetString("VideoIsNotBeingSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volume value should be between [0, 100].
        /// </summary>
        internal static string VolumeValueError {
            get {
                return ResourceManager.GetString("VolumeValueError", resourceCulture);
            }
        }
    }
}
