//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP.VenueService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Storage.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Venue Service data file..
        /// </summary>
        internal static string CreatingVenueServiceDataFile {
            get {
                return ResourceManager.GetString("CreatingVenueServiceDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data file exists.  Skipping creating file..
        /// </summary>
        internal static string DataFileExistsSkippingCreatingFile {
            get {
                return ResourceManager.GetString("DataFileExistsSkippingCreatingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File filePath could not be opened for both read &amp; write..
        /// </summary>
        internal static string FileFilepathCouldNotBeOpened {
            get {
                return ResourceManager.GetString("FileFilepathCouldNotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the file security for the venueservice.dat file failed.  This may be caused by the Internet Guest Account not being present or properly named. 
        ///
        ///For Venue Service to work properly, the data file must be modifiable by the Internet Guest Account. You must add &quot;modify&quot; permissions on the file for the Internet Guest Account..
        /// </summary>
        internal static string FileSecurityChangesFailedText {
            get {
                return ResourceManager.GetString("FileSecurityChangesFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Security Changes Failed.
        /// </summary>
        internal static string FileSecurityChangesFailedTitle {
            get {
                return ResourceManager.GetString("FileSecurityChangesFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS version must be WindowsXP or greater..
        /// </summary>
        internal static string OSVersion {
            get {
                return ResourceManager.GetString("OSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating data structures after external write.  LastWriteTime: {0}.
        /// </summary>
        internal static string UpdatingDataStructures {
            get {
                return ResourceManager.GetString("UpdatingDataStructures", resourceCulture);
            }
        }
    }
}
