//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP.ReflectorService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSR.LST.ConferenceXP.ReflectorService.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator role is required to install/uninstall Reflector Service..
        /// </summary>
        internal static string AdministratorRoleIsRequired {
            get {
                return ResourceManager.GetString("AdministratorRoleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP Reflector.
        /// </summary>
        internal static string ConferencexpReflector {
            get {
                return ResourceManager.GetString("ConferencexpReflector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error adding this application to your firewall&apos;s exception list.  Please add the application manually to your firewall.
        ///
        ///
        ///Exception error message: {0}.
        /// </summary>
        internal static string FirewallExceptionFailedAddingApplication {
            get {
                return ResourceManager.GetString("FirewallExceptionFailedAddingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error removing this application from your firewall&apos;s exception list.  Please remove the application manually to your firewall.
        ///
        ///
        ///Exception error message: {0}.
        /// </summary>
        internal static string FirewallExceptionFailedRemovingApplication {
            get {
                return ResourceManager.GetString("FirewallExceptionFailedRemovingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall Exception Failed.
        /// </summary>
        internal static string FirewallExceptionFailedTitle {
            get {
                return ResourceManager.GetString("FirewallExceptionFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation will now add this application to your Windows Firewall Exceptions list..
        /// </summary>
        internal static string FirewallText {
            get {
                return ResourceManager.GetString("FirewallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall.
        /// </summary>
        internal static string FirewallTitle {
            get {
                return ResourceManager.GetString("FirewallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was installed successfully, but the service could not be started. 
        ///
        ///Exception:
        ///{0}.
        /// </summary>
        internal static string ServiceStartFailureText {
            get {
                return ResourceManager.GetString("ServiceStartFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Start Failure.
        /// </summary>
        internal static string ServiceStartFailureTitle {
            get {
                return ResourceManager.GetString("ServiceStartFailureTitle", resourceCulture);
            }
        }
    }
}
