//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP.VenueService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSR.LST.ConferenceXP.VenueService.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP Venue Service
        ///Microsoft Research &amp; UW Center for Collaborative Technology
        ///
        ///{0}
        ///
        ///For more information, see http://cct.cs.washington.edu/downloads/CXP.
        /// </summary>
        internal static string AboutConferencexpVenueServiceText {
            get {
                return ResourceManager.GetString("AboutConferencexpVenueServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ConferenceXP Venue Service.
        /// </summary>
        internal static string AboutConferencexpVenueServiceTitle {
            get {
                return ResourceManager.GetString("AboutConferencexpVenueServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced....
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Venue Settings.
        /// </summary>
        internal static string AdvancedVenueSettings {
            get {
                return ResourceManager.GetString("AdvancedVenueSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Picture....
        /// </summary>
        internal static string ChoosePicture {
            get {
                return ResourceManager.GetString("ChoosePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Password.
        /// </summary>
        internal static string ClearPassword {
            get {
                return ResourceManager.GetString("ClearPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP Venue Service Manager.
        /// </summary>
        internal static string ConferencexpVenueServiceManager {
            get {
                return ResourceManager.GetString("ConferencexpVenueServiceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to replace the icon for this venue with the default icon?.
        /// </summary>
        internal static string ConfirmDefaultIconRestoreText {
            get {
                return ResourceManager.GetString("ConfirmDefaultIconRestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Default Icon Restore.
        /// </summary>
        internal static string ConfirmDefaultIconRestoreTitle {
            get {
                return ResourceManager.GetString("ConfirmDefaultIconRestoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the identifier expression &quot;{0}&quot;?.
        /// </summary>
        internal static string ConfirmDeleteText {
            get {
                return ResourceManager.GetString("ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the participant &quot;{0}&quot;?.
        /// </summary>
        internal static string ConfirmParticipantDeleteText {
            get {
                return ResourceManager.GetString("ConfirmParticipantDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Participant Delete.
        /// </summary>
        internal static string ConfirmParticipantDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmParticipantDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to replace the identifier expression &quot;{0}&quot; with &quot;{1}&quot;?.
        /// </summary>
        internal static string ConfirmReplaceText {
            get {
                return ResourceManager.GetString("ConfirmReplaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Replace.
        /// </summary>
        internal static string ConfirmReplaceTitle {
            get {
                return ResourceManager.GetString("ConfirmReplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the venue &quot;{0}&quot;?.
        /// </summary>
        internal static string ConfirmVenueDeleteText {
            get {
                return ResourceManager.GetString("ConfirmVenueDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Venue Delete.
        /// </summary>
        internal static string ConfirmVenueDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmVenueDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET &amp; Grids.
        /// </summary>
        internal static string DotNetAndGrids {
            get {
                return ResourceManager.GetString("DotNetAndGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue &quot;{0}&quot; is already using the IP address you specified. Please specify another IP address..
        /// </summary>
        internal static string DuplicateIPAddressText {
            get {
                return ResourceManager.GetString("DuplicateIPAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate IP Address.
        /// </summary>
        internal static string DuplicateIpAddressTitle {
            get {
                return ResourceManager.GetString("DuplicateIpAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue &quot;{0}&quot; is already using the owner you specified. Please specify another owner..
        /// </summary>
        internal static string DuplicateOwnerText {
            get {
                return ResourceManager.GetString("DuplicateOwnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Owner.
        /// </summary>
        internal static string DuplicateOwnerTitle {
            get {
                return ResourceManager.GetString("DuplicateOwnerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Participant.
        /// </summary>
        internal static string EditParticipant {
            get {
                return ResourceManager.GetString("EditParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Venue.
        /// </summary>
        internal static string EditVenue {
            get {
                return ResourceManager.GetString("EditVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  E-Mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail:.
        /// </summary>
        internal static string EmailColon {
            get {
                return ResourceManager.GetString("EmailColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: .*@[O|o]rganization\\.[E|e]du.
        /// </summary>
        internal static string ForExample {
            get {
                return ResourceManager.GetString("ForExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://cct.cs.washington.edu/project-wiki/index.php/ConferenceXP_Venue_Service#Choosing_a_multicast_IP_address.
        /// </summary>
        internal static string HelpURLMulticast {
            get {
                return ResourceManager.GetString("HelpURLMulticast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://cct.cs.washington.edu/project-wiki/index.php/ConferenceXP_Venue_Service.
        /// </summary>
        internal static string HelpURLVenueService {
            get {
                return ResourceManager.GetString("HelpURLVenueService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I choose a multicast IP address?.
        /// </summary>
        internal static string HowDoIChooseAMulticastIP {
            get {
                return ResourceManager.GetString("HowDoIChooseAMulticastIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Identifier.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier:.
        /// </summary>
        internal static string IdentifierColon {
            get {
                return ResourceManager.GetString("IdentifierColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier expression:.
        /// </summary>
        internal static string IdentifierExpression {
            get {
                return ResourceManager.GetString("IdentifierExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;E-Mail&quot; is not a valid e-mail address..
        /// </summary>
        internal static string InvalidEmailInput {
            get {
                return ResourceManager.GetString("InvalidEmailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Identifier&quot; is not a valid e-mail address..
        /// </summary>
        internal static string InvalidIdentifierInput {
            get {
                return ResourceManager.GetString("InvalidIdentifierInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;IP Address&quot; is not a valid IP address. If this is an IPv6 address, the IPv6 protocol should be installed..
        /// </summary>
        internal static string InvalidIPAddressInput {
            get {
                return ResourceManager.GetString("InvalidIPAddressInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Owner&quot; is not a valid e-mail address..
        /// </summary>
        internal static string InvalidOwnerInput {
            get {
                return ResourceManager.GetString("InvalidOwnerInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Port&quot; is not a valid IP port..
        /// </summary>
        internal static string InvalidPortInput {
            get {
                return ResourceManager.GetString("InvalidPortInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  IP Address:.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jay@tailspintoys.com.
        /// </summary>
        internal static string JayAtTailspintoysCom {
            get {
                return ResourceManager.GetString("JayAtTailspintoysCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jay Jones.
        /// </summary>
        internal static string JayJones {
            get {
                return ResourceManager.GetString("JayJones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Participants.
        /// </summary>
        internal static string ManageParticipants {
            get {
                return ResourceManager.GetString("ManageParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Venues.
        /// </summary>
        internal static string ManageVenues {
            get {
                return ResourceManager.GetString("ManageVenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NameColon {
            get {
                return ResourceManager.GetString("NameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Venue.
        /// </summary>
        internal static string NewVenue {
            get {
                return ResourceManager.GetString("NewVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner:.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Editor.
        /// </summary>
        internal static string ParticipantEditor {
            get {
                return ResourceManager.GetString("ParticipantEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Error.
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match!.
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Port:.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5004.
        /// </summary>
        internal static string PortInputDefaultValue {
            get {
                return ResourceManager.GetString("PortInputDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Default.
        /// </summary>
        internal static string RestoreDefault {
            get {
                return ResourceManager.GetString("RestoreDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        internal static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show venue only to participants matching these expressions:.
        /// </summary>
        internal static string ShowVenueOnlyToMatchingParticipants {
            get {
                return ResourceManager.GetString("ShowVenueOnlyToMatchingParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify who can see this venue by participant identifier. Use regular expressions to specify individuals or groups..
        /// </summary>
        internal static string SpecifyWhoCanSeeThisVenue {
            get {
                return ResourceManager.GetString("SpecifyWhoCanSeeThisVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure occurred while accessing the storage file. The Admin Tool will now exit. Check the value of &apos;FilePath&apos; in the application configuration file. 
        ///
        ///Exception:
        ///{0}.
        /// </summary>
        internal static string StorageFailureText {
            get {
                return ResourceManager.GetString("StorageFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Failure.
        /// </summary>
        internal static string StorageFailureTitle {
            get {
                return ResourceManager.GetString("StorageFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use encryption.
        /// </summary>
        internal static string UseEncryption {
            get {
                return ResourceManager.GetString("UseEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue Editor.
        /// </summary>
        internal static string VenueEditor {
            get {
                return ResourceManager.GetString("VenueEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Venue Password.
        /// </summary>
        internal static string VenuePassword {
            get {
                return ResourceManager.GetString("VenuePassword", resourceCulture);
            }
        }
    }
}
