//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSR.LST.ConferenceXP.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Accept.
        /// </summary>
        internal static string AcceptHotkey {
            get {
                return ResourceManager.GetString("AcceptHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add files....
        /// </summary>
        internal static string AddFilesHotkey {
            get {
                return ResourceManager.GetString("AddFilesHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad&amp;vanced.
        /// </summary>
        internal static string AdvancedHotkey {
            get {
                return ResourceManager.GetString("AdvancedHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings.
        /// </summary>
        internal static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP: {0}
        ///ID: {1}
        ///E-Mail: {2}
        ///Phone: {3}.
        /// </summary>
        internal static string AvatarTipText {
            get {
                return ResourceManager.GetString("AvatarTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/s.
        /// </summary>
        internal static string Bps {
            get {
                return ResourceManager.GetString("Bps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string CancelHotkey {
            get {
                return ResourceManager.GetString("CancelHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capability name: {0}
        ///Payload type: {1}.
        /// </summary>
        internal static string CapabilityNamePayloadType {
            get {
                return ResourceManager.GetString("CapabilityNamePayloadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capability received.
        /// </summary>
        internal static string CapabilityReceived {
            get {
                return ResourceManager.GetString("CapabilityReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file is corrupt.
        /// </summary>
        internal static string ConfigurationFileCorrupt {
            get {
                return ResourceManager.GetString("ConfigurationFileCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enable FEC.
        /// </summary>
        internal static string EnableFECHotkey {
            get {
                return ResourceManager.GetString("EnableFECHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        internal static string FileColon {
            get {
                return ResourceManager.GetString("FileColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} no longer exists!{1}Skip this file and continue?.
        /// </summary>
        internal static string FileNoLongerExists {
            get {
                return ResourceManager.GetString("FileNoLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File received.
        /// </summary>
        internal static string FileReceived {
            get {
                return ResourceManager.GetString("FileReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: {0} KB.
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Transfer.
        /// </summary>
        internal static string FileTransfer {
            get {
                return ResourceManager.GetString("FileTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File transfer completed.
        /// </summary>
        internal static string FileTransferCompleted {
            get {
                return ResourceManager.GetString("FileTransferCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Install.
        /// </summary>
        internal static string InstallHotkey {
            get {
                return ResourceManager.GetString("InstallHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        internal static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max bandwidth:.
        /// </summary>
        internal static string MaxBandwidth {
            get {
                return ResourceManager.GetString("MaxBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet implemented.
        /// </summary>
        internal static string NotYetImplemented {
            get {
                return ResourceManager.GetString("NotYetImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string OKHotkey {
            get {
                return ResourceManager.GetString("OKHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string PercentSign {
            get {
                return ResourceManager.GetString("PercentSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reject.
        /// </summary>
        internal static string RejectHotkey {
            get {
                return ResourceManager.GetString("RejectHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string RemoveHotkey {
            get {
                return ResourceManager.GetString("RemoveHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected files:.
        /// </summary>
        internal static string SelectedFiles {
            get {
                return ResourceManager.GetString("SelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file(s).
        /// </summary>
        internal static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send done.
        /// </summary>
        internal static string SendDone {
            get {
                return ResourceManager.GetString("SendDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send files.
        /// </summary>
        internal static string SendFiles {
            get {
                return ResourceManager.GetString("SendFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send files to multiple users via multicast.
        /// </summary>
        internal static string SendFilesToMultipleUsers {
            get {
                return ResourceManager.GetString("SendFilesToMultipleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Send.
        /// </summary>
        internal static string SendHotkey {
            get {
                return ResourceManager.GetString("SendHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending file....
        /// </summary>
        internal static string SendingFile {
            get {
                return ResourceManager.GetString("SendingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending file {0}. Please wait....
        /// </summary>
        internal static string SendingFilePleaseWait {
            get {
                return ResourceManager.GetString("SendingFilePleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings will take effect next time you start this capability.
        /// </summary>
        internal static string TheseSettingsWillTakeEffect {
            get {
                return ResourceManager.GetString("TheseSettingsWillTakeEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user has just sent you a capability.
        /// </summary>
        internal static string UserSentYouCapability {
            get {
                return ResourceManager.GetString("UserSentYouCapability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user has just sent you a file.
        /// </summary>
        internal static string UserSentYouFile {
            get {
                return ResourceManager.GetString("UserSentYouFile", resourceCulture);
            }
        }
    }
}
