//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneNoteCapabilityViewer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: {0}.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Blank&gt;.
        /// </summary>
        internal static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Checkbox &gt;.
        /// </summary>
        internal static string Checkbox {
            get {
                return ResourceManager.GetString("Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Combo Box &gt;.
        /// </summary>
        internal static string ComboBox {
            get {
                return ResourceManager.GetString("ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document from a new author is being received. Please select or type the name of the Section in which you would like the notes to be placed..
        /// </summary>
        internal static string DocumentFromNewAuthor {
            get {
                return ResourceManager.GetString("DocumentFromNewAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in opening {0}, error message: {1}.
        /// </summary>
        internal static string ErrorInOpeningFile {
            get {
                return ResourceManager.GetString("ErrorInOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you see this form, it&apos;s a bug.  If you close it, the capability will die..
        /// </summary>
        internal static string IfYouSeeThisFormMessage {
            get {
                return ResourceManager.GetString("IfYouSeeThisFormMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Label &gt;.
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote 2003 Warning.
        /// </summary>
        internal static string OneNote2003WarningKey {
            get {
                return ResourceManager.GetString("OneNote2003WarningKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP has detected OneNote 2003 is installed.  CXP offers special functionality with OneNote, but OneNote 2003 Service Pack 1 must be installed.  You can go to officeupdate.microsoft.com to install OneNote SP1.
        ///
        /// NOTE that you MUST run OneNote once to initialize it before CXP will recognize it.
        ///
        /// After installing OneNote SP1, the OneNote Capability will be available under Settings -&gt; RTDocument Viewer..
        /// </summary>
        internal static string OneNote2003WarningMsg {
            get {
                return ResourceManager.GetString("OneNote2003WarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote 2007 Warning.
        /// </summary>
        internal static string OneNote2007WarningKey {
            get {
                return ResourceManager.GetString("OneNote2007WarningKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConferenceXP has detected OneNote 2007 is installed but there was an error initializing it.  Please make sure you have the most recent updates from officeupdate.microsoft.com.
        ///
        /// NOTE that you MUST run OneNote once to initialize it before CXP will recognize it.
        ///
        /// After updates, the OneNote Capability will be available under Settings -&gt; RTDocument Viewer..
        /// </summary>
        internal static string OneNote2007WarningMsg {
            get {
                return ResourceManager.GetString("OneNote2007WarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote Importer.
        /// </summary>
        internal static string OneNoteImporter {
            get {
                return ResourceManager.GetString("OneNoteImporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwite File?.
        /// </summary>
        internal static string OverwiteFile {
            get {
                return ResourceManager.GetString("OverwiteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent TOCNode for Page not found..
        /// </summary>
        internal static string ParentTocNodeNotFound {
            get {
                return ResourceManager.GetString("ParentTocNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid response..
        /// </summary>
        internal static string PleaseEnterAValidResponse {
            get {
                return ResourceManager.GetString("PleaseEnterAValidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document being received has the same title as another document in this folder.  Would you like to overwrite: &quot;{0}&quot;?
        ///
        ///Select &apos;Yes&apos; to overwrite the file and &apos;No&apos; to change the name automatically..
        /// </summary>
        internal static string SameTitleError {
            get {
                return ResourceManager.GetString("SameTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this setting for this author..
        /// </summary>
        internal static string SaveThisSetting {
            get {
                return ResourceManager.GetString("SaveThisSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Auto-sync&apos;d.
        /// </summary>
        internal static string StayAutoSynched {
            get {
                return ResourceManager.GetString("StayAutoSynched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync to Instructor.
        /// </summary>
        internal static string SyncToInstructor {
            get {
                return ResourceManager.GetString("SyncToInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whiteboard Session {0}.
        /// </summary>
        internal static string WhiteboardSession {
            get {
                return ResourceManager.GetString("WhiteboardSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whiteboard 1.
        /// </summary>
        internal static string WhiteboardTitle {
            get {
                return ResourceManager.GetString("WhiteboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why hello there!.
        /// </summary>
        internal static string WhyHelloThere {
            get {
                return ResourceManager.GetString("WhyHelloThere", resourceCulture);
            }
        }
    }
}
