//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSR.LST.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Privileges Required.
        /// </summary>
        internal static string AdministratorPrivilegesRequired {
            get {
                return ResourceManager.GetString("AdministratorPrivilegesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not call AddPortToOldFirewall or RemovePortFromOldFirewall on a comptuer with an XP SP2-compatible firewall..
        /// </summary>
        internal static string DoNotCallAddPortToOldFirewall {
            get {
                return ResourceManager.GetString("DoNotCallAddPortToOldFirewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has encountered the following error:
        ///
        ///{1}.
        /// </summary>
        internal static string ErrorMessageToUser {
            get {
                return ResourceManager.GetString("ErrorMessageToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main or manual.
        /// </summary>
        internal static string MainOrManual {
            get {
                return ResourceManager.GetString("MainOrManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-CLS compliant exception: ExceptionType:{0}, ExceptionString:{1}.
        /// </summary>
        internal static string NonCLSCompliantException {
            get {
                return ResourceManager.GetString("NonCLSCompliantException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a firewall port map to be added, the OS must be Windows XP SP2 or greater..
        /// </summary>
        internal static string OSMustBeWindowsXPSP2OrGreater {
            get {
                return ResourceManager.GetString("OSMustBeWindowsXPSP2OrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS version must be WindowsXP or greater..
        /// </summary>
        internal static string OSVersion {
            get {
                return ResourceManager.GetString("OSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pool or finalizer.
        /// </summary>
        internal static string PoolOrFinalizer {
            get {
                return ResourceManager.GetString("PoolOrFinalizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arrays of ports and port types should be the same length..
        /// </summary>
        internal static string PortsAndPortTypesSameLength {
            get {
                return ResourceManager.GetString("PortsAndPortTypesSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product version: {0}.
        /// </summary>
        internal static string ProductVersion {
            get {
                return ResourceManager.GetString("ProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That protocol is not supported by this firewall wrapper.  Only TCP &amp; UDP are supported..
        /// </summary>
        internal static string ProtocolIsNotSupported {
            get {
                return ResourceManager.GetString("ProtocolIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender string: {0}.
        /// </summary>
        internal static string SenderString {
            get {
                return ResourceManager.GetString("SenderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender type: {0}.
        /// </summary>
        internal static string SenderType {
            get {
                return ResourceManager.GetString("SenderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread type:.
        /// </summary>
        internal static string ThreadType {
            get {
                return ResourceManager.GetString("ThreadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type not handled was provided as the ControlType..
        /// </summary>
        internal static string TypeNotHandledWasProvided {
            get {
                return ResourceManager.GetString("TypeNotHandledWasProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be an Administrator to install the Unhandled Exception Handler..
        /// </summary>
        internal static string YouMustBeAnAdministratorToInstall {
            get {
                return ResourceManager.GetString("YouMustBeAnAdministratorToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be an administrator to modify the firewall settings..
        /// </summary>
        internal static string YouMustBeAnAdministratorToModify {
            get {
                return ResourceManager.GetString("YouMustBeAnAdministratorToModify", resourceCulture);
            }
        }
    }
}
